//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR
{
    using System;
    using System.Collections.Generic;
    
    public partial class region_info
    {
        public int id { get; set; }
        public string region_name_en { get; set; }
        public string region_name_ru { get; set; }
        public Nullable<int> subject_code { get; set; }
        public string code { get; set; }
        public string code_okato { get; set; }
        public string iso { get; set; }
    }
}
